image:
  name: gitpod/workspace-java:latest
  init: true

tasks:
  - command: |
      mvn clean install

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.vscode-yaml
    - ms-python.python
    - vscjava.vscode-maven
