image: gitpod/workspace-java:latest

tasks:
  - name: Build Project
    command: mvn clean install

  - name: Run TestNG Tests
    command: mvn test -DsuiteXmlFile=testng.xml
    # Optional: Define the port if your application needs to expose it


vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.vscode-yaml
    - vscjava.vscode-maven
